on:
  pull_request:
    branches:
      - master

name: "Github CI CD"
env:
  dotnet-version: '8.0.x'
  build-configuration: 'Release'
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.dotnet-version}}
      
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Restore packages
        run: dotnet restore
          
      - name: build solution
        run: dotnet build --no-restore --configuration ${{env.build-configuration}}
          
      - name: Test the solution
        run: >
          dotnet test 
          --no-build 
          --configuration ${{env.build-configuration}}
          --collect:"XPlat Code Coverage"
          --logger 'trx' 
          
      - name: publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: test-results
          path: "**/*.trx"
            
      - name: publish  the coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: "**/coverage.cobertura.xml"      
          
  